services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
